blank_issues_enabled: true
contact_links:
  - name: GitHub Discussions
    url: https://github.com/spp-programming/SPPrep-New-Tab-Next/discussions
    about: Questions, general discussions, etc. should go here.